// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DownloadBook(arg1:string,arg2:string):Promise<void>;

export function GetBookDetail(arg1:string):Promise<main.BookDetail>;

export function GetConfig():Promise<main.Config>;

export function GetCookie():Promise<string>;

export function NotifyProgress(arg1:main.DownloadProgress):Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SearchBooks(arg1:string):Promise<Array<main.Book>>;
