// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadBook(arg1, arg2) {
  return window['go']['main']['App']['DownloadBook'](arg1, arg2);
}

export function GetBookDetail(arg1) {
  return window['go']['main']['App']['GetBookDetail'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCookie() {
  return window['go']['main']['App']['GetCookie']();
}

export function NotifyProgress(arg1) {
  return window['go']['main']['App']['NotifyProgress'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SearchBooks(arg1) {
  return window['go']['main']['App']['SearchBooks'](arg1);
}
